Collaborate/urls.py
from django.conf.urls import url
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

from Collaborate import settings
from CollaborateApp import urls

urlpatterns = [
    path('admin/', admin.site.urls),
    url(r'', include(urls))
]
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

CollaborateApp/urls.py
from django.conf.urls.static import static
from django.views.decorators.csrf import csrf_exempt

from CollaborateApp.views import *
from CollaborateApp.rest_apis import *
from django.urls import path

from CollaborateApp.views.authentication import LoginView, SignupView, log_out

app_name = 'collaborate'

urlpatterns = [
    path('api/get_user/<str:username>', GetUserDetails.as_view(), name='get_user'),
    path('api/add_user/', AddUser.as_view(), name='add_user'),
    path('upload_file/<int:groupid>', model_form_upload, name='file_form'),
    path('api/files/<int:group>/', GetFiles.as_view(), name='group_files'),
    path('api/groups/<int:group>/', GroupDetails.as_view(), name='group_details'),
    path('api/groups/add/', AddGroup.as_view(), name='add_group'),
    path('api/groups/delete/<int:group>/', DeleteGroup.as_view(), name='delete_group'),
    path('api/users/user_details/', load_groups, name='load_user_details'),
    path('api/file/get/<int:fileid>/', GetFileData.as_view(), name='get_file_data'),
    path('api/file/edit/<int:fileid>/', csrf_exempt(EditFile.as_view()), name='edit_file'),
    path('api/file/delete/<int:fileid>/', DeleteFile.as_view(), name='delete_file'),
    path('api/file/download/<int:fileid>/', DownloadFile.as_view(), name='download_file'),
    path('api/<int:group>/add_user/', AddToGroup.as_view(), name='add_to_group'),
    path('api/<int:group>/remove_user/<str:user>', DeleteFromGroup.as_view(), name='delete_from_group'),
    path('<str:username>/workspace/', DisplayGroups.as_view(), name='ui_workspace_groups'),
    path('login/', LoginView.as_view(), name='login'),
    path('signup/', SignupView.as_view(), name='signup'),
    path('logout/', log_out, name='logout'),
    path('sample/', sampleview, name='college_details_rest'),
    path(r'', homeview, name='home',),
    path('userhome/', load_user_home, name='user_home'),
    path('change_password_page/', fetch_change_password_page, name='fetch_change_password_page'),
    path('edit_profile_page/', fetch_edit_profile_page, name='fetch_edit_profile_page'),
    path('change_password/', ChangePassword.as_view(), name='change_password'),
    path('edit_profile/', fetch_edit_profile_page, name='edit_profile'),
    path('reset_password/', ResetPassword.as_view(), name='reset_password'),
    path('send_reset_code/', EmailResetCode.as_view(), name='send_reset_code'),
    path('api/get_users_by_keyword/', GetUsersByKeyword.as_view(), name='get_users_by_keyword'),
    path('api/execute/', ExecuteCode.as_view(), name='execution'),
]+ static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

CollaborateApp/models.py
from django.contrib.auth.models import Group
from django.db import models

# Create your models here.
from django.db.models import ForeignKey, CASCADE, DateTimeField, FileField, EmailField, IntegerField
from django.utils.timezone import now


def get_path(instance, filename):

    return '{0}/{1}'.format(instance.group.id,filename)

class Files(models.Model):
    group = ForeignKey(Group,on_delete=CASCADE)
    last_modified = DateTimeField(default=now())
    url = FileField(upload_to=get_path)


class PasswordResetStats(models.Model):
    email = EmailField()
    reset_code = IntegerField()

CollaborateApp/forms/file_form.py
from django.forms import ModelForm

from CollaborateApp.models import Files


class FileForm(ModelForm):
    class Meta:
        model = Files
        fields = ('url', )

CollaborateApp/forms/login_form.py
from django.forms import Form, CharField, TextInput, PasswordInput


class LoginForm(Form):
    username=CharField(
        required=True,
        widget=TextInput(attrs={'class': 'form-control', 'placeholder': 'Username', 'required': 'true'})
    )
    password=CharField(
        required=True,
        widget=PasswordInput(attrs={'class': 'form-control', 'placeholder': 'Password', 'required': 'true', 'minlength': '8'})
    )

CollaborateApp/forms/signup_form.py
from django import forms


class SignupForm(forms.Form):
    first_name=forms.CharField(
        max_length=20,
        required=True,
        widget=forms.TextInput(attrs={'class': 'form-control', 'placeholder': 'First Name', 'required': 'true', 'minlength': '4'})
    )
    last_name = forms.CharField(
        max_length=20,
        required=True,
        widget=forms.TextInput(attrs={'class': 'form-control', 'placeholder': 'Last Name', 'required': 'true', 'minlength': '4'})
    )
    username = forms.CharField(
        max_length=20,
        required=True,
        widget=forms.TextInput(attrs={'class': 'form-control', 'placeholder': 'Username', 'required': 'true', 'minlength': '6'})
    )
    password = forms.CharField(
        max_length=20,
        required=True,
        widget=forms.PasswordInput(attrs={'class': 'form-control', 'placeholder': 'Password', 'required': 'true', 'minlength': '8'})
    )
    email = forms.EmailField(
        max_length=80,
        required=True,
        widget=forms.EmailInput(attrs={'class': 'form-control', 'placeholder': 'Email ID', 'required': 'true', 'minlength': '8'})
    )

CollaborateApp/views.py
from django.shortcuts import render

# Create your views here.

CollaborateApp/views/authentication.py
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.models import User
from django.shortcuts import render, redirect
from django.views.generic.base import View

from CollaborateApp.forms import LoginForm
from CollaborateApp.forms.signup_form import SignupForm


class LoginView(View):
    def get(self, request, *args, **kwargs):
        form = LoginForm()
        return render(request,'login.html',{'form':form,'message':None})

    def post(self, request, *args, **kwargs):
        form = LoginForm(request.POST)
        if form.is_valid():
            values = list(form.cleaned_data.values())
            user = authenticate(request, username=values[0], password=values[1])
            if user is not None:
                login(request, user)
                return redirect('collaborate:ui_workspace_groups', username=request.user.username)
            else:
                try:
                    user = User.objects.get(email=values[0])
                    user_auth = authenticate(request, username=user.username, password=values[1])
                    if user_auth is None:
                        return render(request, 'login.html', {'form': form, 'message': 'Invalid credentials !' + values[
                            0] + ' ' + user.username})
                    else:
                        login(request, user_auth)
                        return redirect('collaborate:ui_workspace_groups', username=request.user.username)
                except Exception:
                    return render(request, 'login.html', {'form': form, 'message': 'Invalid credentials!'})


class SignupView(View):
    def get(self,request,*args,**kwargs):
        form = SignupForm()
        return render(request, 'signup.html', {'form':form,'errors':None})


def log_out(request):
    logout(request)
    return redirect('collaborate:home')

CollaborateApp/views/displayviews.py
from django.contrib.auth.mixins import LoginRequiredMixin
from django.shortcuts import render
from django.urls import reverse_lazy
from django.views.generic import View
from requests import get as GET


class DisplayGroups(LoginRequiredMixin, View):
    login_url = 'collaborate:login'

    def get(self, request, *args, **kwargs):
        host = request.get_host()
        protocol = ''
        if request.is_secure():
            protocol = 'https://'
        else:
            protocol = 'http://'
        url = protocol + host + str(reverse_lazy('collaborate:get_user', kwargs=kwargs))
        data = GET(url).json()
        groups = data['groups']
        personal_index = 0
        for group in groups:
            if 'personal' in group['name'].lower():
                break
            personal_index += 1
        personal = None
        try:
            personal = groups.pop(personal_index)
        finally:
            return render(
                request,
                template_name='work_area.html',
                context={
                    'groups': groups,
                    'personal': personal
                }
            )

    def post(self, request, *args, **kwargs):
        return self.get(request, *args, **kwargs)

CollaborateApp/views/files.py
import os

from django.contrib.auth.models import Group, User
from django.core.exceptions import ObjectDoesNotExist
from django.shortcuts import redirect, render
from django.template.defaultfilters import register
from django.urls import reverse_lazy
from requests import get

from Collaborate import settings
from CollaborateApp.forms import FileForm
from CollaborateApp.models import Files


@register.filter(name='split')
def split(value):
    return value.split()


def model_form_upload(request, groupid):
    group = Group.objects.get(id=groupid)
    if request.method == 'POST':
        form = FileForm(request.POST, request.FILES)
        form.instance.group = group
        filename = str(groupid) + '/' + str(request.FILES['url'])
        try:
            file = Files.objects.get(url=filename)
            name = file.url.name
            file.delete()
            os.remove(os.path.join(settings.MEDIA_ROOT, name))
        finally:
            if form.is_valid():
                form.save()
                return redirect('collaborate:ui_workspace_groups', username=request.user.username)
    else:
        form = FileForm()
    return render(request, 'model_form_upload.html', {
        'form': form,
        'name': group.name.split()[-1],
        'id': group.id
    })


def sampleview(request):
    return render(request, template_name='work_area.html')


def homeview(request):
    return render(request, template_name='home.html')


def load_user_home(request):
    return render(request, template_name='userhome.html')


def fetch_change_password_page(request):
    return render(request, template_name='change_password.html')


def fetch_edit_profile_page(request):
    data = None
    try:
        user = User.objects.get(username=request.user.username)
        data = dict()
        data['email'] = user.email
        data['first_name'] = user.first_name
        data['last_name'] = user.last_name
    finally:
        return render(request, template_name='edit_profile.html', context=data)


def load_groups(request):
    if request.user.is_authenticated:
        host = request.get_host()
        protocol = ''
        if request.is_secure():
            protocol = 'https://'
        else:
            protocol = 'http://'
        url = protocol + host + str(reverse_lazy('collaborate:get_user', kwargs={'username':request.user.username}))
        data = get(url).json()
        groups = data['groups']
        personal_index = 0
        for group in groups:
            if 'personal' in group['name'].lower():
                break
            personal_index += 1
        try:
            groups.pop(personal_index)
        finally:
            return render(
                request,
                template_name='view_groups.html',
                context={
                    'groups': groups
                }
            )

CollaborateApp/templates/base.html
{% load static %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="shortcut icon" href="{% static 'imgs/collaborate_logo.png' %}" />
    <title>Collaborate
        {% if request.user.is_authenticated %}
            - {{ request.user.last_name}}
        {% endif %}
    </title>
    <link href="{% static 'theme/3024-day.css' %}" rel="stylesheet"/>
    <link href="{% static 'theme/3024-night.css' %}" rel="stylesheet"/>
    <link href="{% static 'theme/abcdef.css' %}" rel="stylesheet"/>
    <link href="{% static 'theme/ambiance.css' %}" rel="stylesheet"/>
    <link href="{% static 'theme/base16-dark.css' %}" rel="stylesheet"/>
    <link href="{% static 'theme/bespin.css' %}" rel="stylesheet"/>
    <link href="{% static 'theme/base16-light.css' %}" rel="stylesheet"/>
    <link href="{% static 'theme/blackboard.css' %}" rel="stylesheet"/>
    <link href="{% static 'theme/cobalt.css' %}" rel="stylesheet"/>
    <link href="{% static 'theme/colorforth.css' %}" rel="stylesheet"/>
    <link href="{% static 'theme/dracula.css' %}" rel="stylesheet"/>
    <link href="{% static 'theme/duotone-dark.css' %}" rel="stylesheet"/>
    <link href="{% static 'theme/duotone-light.css' %}" rel="stylesheet"/>
    <link href="{% static 'theme/eclipse.css' %}" rel="stylesheet"/>
    <link href="{% static 'theme/elegant.css' %}" rel="stylesheet"/>
    <link href="{% static 'theme/erlang-dark.css' %}" rel="stylesheet"/>
    <link href="{% static 'theme/gruvbox-dark.css' %}" rel="stylesheet"/>
    <link href="{% static 'theme/hopscotch.css' %}" rel="stylesheet"/>
    <link href="{% static 'theme/icecoder.css' %}" rel="stylesheet"/>
    <link href="{% static 'theme/isotope.css' %}" rel="stylesheet"/>
    <link href="{% static 'theme/lesser-dark.css' %}" rel="stylesheet"/>
    <link href="{% static 'theme/liquibyte.css' %}" rel="stylesheet"/>
    <link href="{% static 'theme/lucario.css' %}" rel="stylesheet"/>
    <link href="{% static 'theme/material.css' %}" rel="stylesheet"/>
    <link href="{% static 'theme/mbo.css' %}" rel="stylesheet"/>
    <link href="{% static 'theme/mdn-like.css' %}" rel="stylesheet"/>
    <link href="{% static 'theme/midnight.css' %}" rel="stylesheet"/>
    <link href="{% static 'theme/monokai.css' %}" rel="stylesheet"/>
    <link href="{% static 'theme/neat.css' %}" rel="stylesheet"/>
    <link href="{% static 'theme/neo.css' %}" rel="stylesheet"/>
    <link href="{% static 'theme/night.css' %}" rel="stylesheet"/>
    <link href="{% static 'theme/oceanic-next.css' %}" rel="stylesheet"/>
    <link href="{% static 'theme/panda-syntax.css' %}" rel="stylesheet"/>
    <link href="{% static 'theme/paraiso-dark.css' %}" rel="stylesheet"/>
    <link href="{% static 'theme/paraiso-light.css' %}" rel="stylesheet"/>
    <link href="{% static 'theme/pastel-on-dark.css' %}" rel="stylesheet"/>
    <link href="{% static 'theme/railscasts.css' %}" rel="stylesheet"/>
    <link href="{% static 'theme/rubyblue.css' %}" rel="stylesheet"/>
    <link href="{% static 'theme/seti.css' %}" rel="stylesheet"/>
    <link href="{% static 'theme/shadowfox.css' %}" rel="stylesheet"/>
    <link href="{% static 'theme/solarized.css' %}" rel="stylesheet"/>
    <link href="{% static 'theme/the-matrix.css' %}" rel="stylesheet"/>
    <link href="{% static 'theme/tomorrow-night-bright.css' %}" rel="stylesheet"/>
    <link href="{% static 'theme/tomorrow-night-eighties.css' %}" rel="stylesheet"/>
    <link href="{% static 'theme/ttcn.css' %}" rel="stylesheet"/>
    <link href="{% static 'theme/twilight.css' %}" rel="stylesheet"/>
    <link href="{% static 'theme/vibrant-ink.css' %}" rel="stylesheet"/>
    <link href="{% static 'theme/xq-dark.css' %}" rel="stylesheet"/>
    <link href="{% static 'theme/xq-light.css' %}" rel="stylesheet"/>
    <link href="{% static 'theme/yeti.css' %}" rel="stylesheet"/>
    <link href="{% static 'theme/idea.css' %}" rel="stylesheet"/>
    <link href="{% static 'theme/darcula.css' %}" rel="stylesheet"/>
    <link href="{% static 'theme/zenburn.css' %}" rel="stylesheet"/>
    <link href='https://fonts.googleapis.com/css?family=Comfortaa' rel='stylesheet'>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="{% static 'lib/codemirror.css' %}">
    <script src="{% static 'lib/codemirror.js' %}"></script>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
    <script src="{% static 'lib/jquery_transport.js' %}"></script>
    <link href='https://fonts.googleapis.com/css?family=Khula' rel='stylesheet'>
    <style>
        a.menu_nav, a.menu_nav:visited, a.menu_nav:link
        {
            color:darkgrey;
            text-decoration:none;
        }
        a.menu_nav:hover, a.menu_nav:active
        {
            color:white;
            text-decoration:none;
        }
        a.home_nav
        {
            color:white;
            text-decoration:none;
        }
        .intro
        {
            border-radius:10px;
            padding:20px;
            color:white;
        }
        ul.groups li
        {
            margin-left:10px;
            padding:10px;
            cursor:pointer;
            display:block;
        }
        ul.files li
        {
            margin-left:5px;
            padding:5px;
            cursor:pointer;
            display:block;
        }
        .CodeMirror
        {
            height: 100%;
            width: 100%;
        }
        a.utility_nav
        {
            text-decoration:none;
            cursor:pointer;
        }
        label.form_label,input.form_text
        {
            display:inline;
            margin-right:15px;
        }

        .load {
            -webkit-animation: spin 2s linear infinite;
            animation: spin 2s linear infinite;
        }

        @-webkit-keyframes spin {
            100% { -webkit-transform: rotate(360deg); }
        }

        @keyframes spin {
            100% { transform: rotate(360deg); }
        }
    </style>
    {% block javascript %}
    <script>
        var load_home_url = "{% url 'collaborate:user_home' %}";
        var load_upload_url = "{% url 'collaborate:file_form' groupid=1%}";
        var load_files_url = "{% url 'collaborate:group_files' group=1 %}";
        var save_file_url = "{% url 'collaborate:edit_file' fileid=1 %}";
        var delete_file_url = "{% url 'collaborate:delete_file' fileid=1 %}";
        var download_file_url = "{% url 'collaborate:download_file' fileid=1 %}";
        var load_file_url = "{% url 'collaborate:get_file_data' fileid=1 %}";
        var create_group_url = "{% url 'collaborate:add_group' %}";
        var load_group_url = "{% url 'collaborate:group_details' group=1 %}";
        var view_group_details_url = "{% url 'collaborate:load_user_details' %}";
        var delete_group_url = "{% url 'collaborate:delete_group' group=1 %}";
        var add_user_to_group_url = "{% url 'collaborate:add_to_group' group=1 %}";
        var delete_from_group_url = "{% url 'collaborate:delete_from_group' group=1 user='h' %}";
        var get_change_password_url = "{% url 'collaborate:fetch_change_password_page' %}";
        var get_edit_profile_url = "{% url 'collaborate:fetch_edit_profile_page' %}";
        var change_password_url = "{% url 'collaborate:change_password' %}";
        var collaborate_home_url = "{% url 'collaborate:home' %}";
        var edit_profile_url = "{% url 'collaborate:edit_profile' %}";
        var get_users_by_keyword_url = "{% url 'collaborate:get_users_by_keyword' %}";
        var send_email_url = "{% url 'collaborate:send_reset_code' %}";
        var reset_password_url = "{% url 'collaborate:reset_password' %}";
        var signup_url = "{% url 'collaborate:add_user' %}";
        var file_icon_url = "{% static 'exts/9.png' %}";
        var code_execution_url = "{% url 'collaborate:execution' %}";
    </script>
    {% endblock %}
    <script src="{% static 'collaborate/workarea.js' %}"></script>
    <script src="{% static 'collaborate/login.js' %}"></script>
    <script src="{% static 'collaborate/signup.js' %}"></script>
</head>
<body onloadeddata="close_loader()">
    <div class="navbar navbar-inverse navbar-fixed-top navbar-responsive" style="border-radius:0px;min-width:100%;max-height:55px; font-family:Comfortaa;">
        <div class="navbar-header">
            <a href="{% url 'collaborate:home' %}" style="text-decoration:none;">
                <div class="navbar-brand">
                    <img src="{% static 'imgs/collaborate_logo.png' %}" height="30px" width="40px" style="display:inline"/>
                    Collaborate
                </div>
            </a>
        </div>
        {% if request.user.is_authenticated %}
            <ul class="nav navbar-nav navbar-right" style="margin-right:10px;">
                <li><a href="{% url 'collaborate:home' %}"><span class="glyphicon glyphicon-home"></span> Home </a> </li>
                <li><a href="{% url 'collaborate:ui_workspace_groups' username=request.user.username %}">{{ request.user.first_name }} {{ request.user.last_name }}</a></li>
                <li><a href="{% url 'collaborate:logout' %}"><span class="glyphicon glyphicon-log-out"></span> Logout</a></li>
            </ul>
        {% else %}
        <ul class="nav navbar-nav navbar-right" style="margin-right:10px;">
            <li><a href="{% url 'collaborate:home' %}"><span class="glyphicon glyphicon-home"></span> Home </a> </li>
            <li><a href="{% url 'collaborate:signup' %}"><span class="glyphicon glyphicon-user"></span> Register</a></li>
            <li><a href="{% url 'collaborate:login' %}"><span class="glyphicon glyphicon-log-in"></span> Login</a></li>
        </ul>
        {% endif %}
    </div>
    <div style="margin-top:50px;width:100%;">
        {% block content %}
        {% endblock %}
    </div>
</body>
</html>

CollaborateApp/templates/change_password.html
<center><h3 style="color:orange;font-family:Comfortaa;"><b>Change Password</b></h3><br><br>
<form onsubmit="return false" id="change_password_form" style="font-family:Khula;">
    <table>
        <tr>
            <td style="padding:10px;"><label for="old_password">Old Password:</label></td>
            <td style="padding:10px;"><input type="password" required class="form-control form_text" id="old_password" placeholder="Existing Password" minlength="8"></td>
            <td></td>
        </tr>
        <tr>
            <td style="padding:10px;"><label for="new_password">New Password:</label></td>
            <td style="padding:10px;"><input type="password" required class="form-control form_text" id="new_password" placeholder="New Password" onkeyup="check_match()" minlength="8"></td>
            <td></td>
        </tr>
        <tr>
            <td style="padding:10px;"><label for="confirm_password">Confirm Password:</label></td>
            <td style="padding:10px;">
                <input type="password" required class="form-control form_text" id="confirm_password" placeholder="Confirm Password" onkeyup="check_match()" minlength="8">
            </td>
            <td style="display:none;" id="password_match"><h5 style="color:red;"><b>Passwords do not match</b></h5></td>
        </tr>
    </table><br>
    <input type="submit" id="change_password_button" class="btn btn-success" value="Change Password" style="margin-left:10px;" onclick="change_password()">
</form>
</center>

CollaborateApp/templates/edit_profile.html
<center><h3 style="color:orange;font-family:Comfortaa;"><b>Edit Profile</b></h3><br><br>
<form onsubmit="return false" id="change_password_form" style="font-family:Khula">
    <table style="width:50%;">
        <tr>
            <td style="padding:10px;"><label for="first_name">First Name:</label></td>
            <td style="padding:10px;"><input type="text" required class="form-control form_text" id="first_name" placeholder="First Name" value="{{ first_name }}" minlength="8"></td>
            <td></td>
        </tr>
        <tr>
            <td style="padding:10px;"><label for="last_name">Last Name:</label></td>
            <td style="padding:10px;"><input type="text" required class="form-control form_text" id="last_name" placeholder="Last Name" value="{{ last_name }}" minlength="8"></td>
        </tr>
        <tr>
            <td style="padding:10px;"><label for="email">Email:</label></td>
            <td style="padding:10px;"><input type="email" required class="form-control form_text" id="email" placeholder="Email" value="{{ email }}" minlength="8"></td>
        </tr>
    </table><br>
    <input type="submit" id="change_password_button" class="btn btn-success" value="Edit Profile" style="margin-left:10px;" onclick="change_password()">
    <h5 id="pass_ack" style="display:inline;margin-left:20px;"><b></b></h5>
</form>
</center>

CollaborateApp/templates/form_add_group.html
<form method="post" action="{% url 'collaborate:add_group'%}" style="font-family:Khula">
    {% csrf_token %}
    <label for="group_name">Name: </label>
    <input required type="text" class="form-control input-sm" name="group_name" style="margin-bottom:10px;" pattern="[A-Za-z0-9_]{6,}" title="Must be of minimum 6 characters. Cannot use spaces. Only _ can be used" placeholder="Group_Name">
    <input type="submit" class="btn btn-success btn-sm" value="Create Group">
    <a class="btn btn-danger btn-sm" onclick="close_group()">Cancel</a>
</form>

CollaborateApp/templates/login.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
    {% if message %}
    <div class="alert alert-danger">
        <strong>{{message}}</strong>
    </div>
    {% else %}
    {% endif %}
    <div class="col-md-3"></div>
    <div class="col-md-6" style="margin-top:30px;font-family:Khula">
        <div class="panel panel-primary">
            <div class="panel-heading" style="font-family:Comfortaa">
                Login
            </div>
            <div class="panel-body">
        <form method="post" style="padding:15px;width:75%;margin-left:10%">
            {% csrf_token %}
            <div class="form-group">
                <label for="{{form.username.id_for_label}}">Username:</label>
                {{form.username}}
            </div>
            <div class="form-group" id="noedit">
                <label for="{{form.password.id_for_label}}">Password:</label>
                {{form.password}}
            </div>
            <center>
                <button type="button" class="btn btn-link" data-toggle="modal" data-target="#myModal">Forgot Password?</button><br>
                <input type="submit" class="btn btn-success" value="Login">&emsp14;
                <a href="{% url 'collaborate:signup' %}" class="btn btn-info">Register</a>
            </center>
        </form>
            </div>
        </div>
    </div>
<div id="myModal" class="modal fade" role="dialog" style="font-family:Khula">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" onclick="reset_form()">&times;</button>
        <h4 class="modal-title" style="font-family:Comfortaa">Reset Password</h4>
      </div>
      <div class="modal-body">
          <form onsubmit="return false" id="verify_email_form" style="padding:10px">
              <label for="forgot_password_email" class="form_label">Email: </label>
              <input type="email" required class="form-control form_text" placeholder="Email" id="forgot_password_email" style="width:50%" minlength="8"><br><br>
              <input type="submit" class="btn btn-success" value="Verify Email" id="verify_email_button" onclick="send_email()">
              <h5 id="email_ack" style="display:inline;margin-left:20px;"><b></b></h5>
          </form>
          <br>
          <form onsubmit="return reset_password()" id="reset_password_form" style="display:none;">
              <table>
                  <tr>
                      <td style="padding:10px;"><label for="reset_code">Reset Code:</label></td>
                      <td style="padding:10px;"><input type="text" required class="form-control" id="reset_code" placeholder="XXXXX" pattern="[0-9]{5}" maxlength="5" minlength="5"></td>
                      <td></td>
                  </tr>
                  <tr>
                      <td style="padding:10px;"><label for="new_password">New Password:</label></td>
                      <td style="padding:10px;"><input type="password" required class="form-control form_text" id="new_password" placeholder="New Password" onkeyup="check_match()" autocomplete="off" minlength="8"></td>
                      <td></td>
                  </tr>
                  <tr>
                      <td style="padding:10px;"><label for="confirm_password">Confirm Password:</label></td>
                      <td style="padding:10px;">
                          <input type="password" required class="form-control form_text" id="confirm_password" placeholder="Confirm Password" onkeyup="check_match()" autocomplete="off" minlength="8">
                      </td>
                      <td style="display:none;" id="password_match"><h5 style="color:red;"><b>Passwords do not match</b></h5></td>
                  </tr>
              </table>
              <input type="submit" id="reset_password_button" class="btn btn-success" value="Reset Password" style="margin-left:10px;" disabled onclick="return reset_password()">
          </form>
          <h5 id="pass_ack" style="display:inline;margin-left:20px;"><b></b></h5>
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-danger" data-dismiss="modal" onclick="reset_form()">Cancel</button>
      </div>
    </div>
  </div>
</div>
{% endblock %}

CollaborateApp/templates/model_form_upload.html
<h5><b style="font-family:Comfortaa">Uploading file to "{{ name }}"</b></h5>
<form method="post" enctype="multipart/form-data" action="{% url 'collaborate:file_form' groupid=id%}" style="font-family:Khula">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit" class="btn btn-success btn-sm">Upload</button>
    <button class="btn btn-danger btn-sm" onclick="close_upload()">Cancel</button>
</form>
<h6><b><u>Note:</u></b> Uploading a file with existing files' name will <b style="color:red">overwrite</b> existing file!</h6>